name: ci

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup Zig Compiler
      #You may pin to the exact commit or the version.
      # uses: mlugg/setup-zig@8d6198c65fb0feaa111df26e6b467fea8345e46f
        uses: mlugg/setup-zig@v2.0.5
        with:
          # Version of the Zig compiler, e.g. "0.13.0" or "0.13.0-dev.351+64ef45eb0". "master" uses the latest nightly build. "latest" uses the latest tagged release. Leave empty to use minimum_zig_version from build.zig.zon, with a fallback to "latest".
          version: "0.14.1"
          
      - name: get sdl
        run: git clone --depth 1 --branch release-3.2.16 https://github.com/libsdl-org/SDL.git
        run: cd SDL
        run: sudo apt-get install build-essential git make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev
        run: cmake -S . -B build
        run: cmake --build build
        run: sudo cmake --install build --prefix /usr



      #- uses: libsdl-org/setup-sdl@main
      #  id: sdl
      #  with:
      #    install-linux-dependencies: true
      #    version: 3.2.16

      - uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: libepoxy-dev libfreetype-dev
          
      - name: build it
        run: ./distrib/makeappdir.sh

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: rathammer_linux_x86_x64.zip
          path: distrib/rathammer_linux_x86_x64.zip

      
