name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps: 
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Zig Compiler
      #You may pin to the exact commit or the version.
      # uses: mlugg/setup-zig@8d6198c65fb0feaa111df26e6b467fea8345e46f
        uses: mlugg/setup-zig@v2.0.5
        with:
          # Version of the Zig compiler, e.g. "0.13.0" or "0.13.0-dev.351+64ef45eb0". "master" uses the latest nightly build. "latest" uses the latest tagged release. Leave empty to use minimum_zig_version from build.zig.zon, with a fallback to "latest".
          version: "0.14.1"
          # Override of Zig download mirror to use, e.g. "https://pkg.machengine.org/zig".
  
